version: '3'
services:
  iotdash:
    container_name: iotdash
    build: ./middleware/iotdash
    restart: always
    tty: true
    privileged: true                           
    command: /sbin/init  
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./app:/app
    ports:
      - "3000:3000"
      - "1001:1883"
      - "9002:9001"
    # working_dir: /app

